mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static #추가
from django.conf import settings #추가

from mysite.views import HomeView
from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='mainpage_ex'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^photo/', include('photo.urls', namespace='photo')), #추가

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) #추가

photo/urls.py
from django.conf.urls import url
from photo.views import *

app_name = 'photo'
urlpatterns = [

    #Example: /
    url(r'^$', AlbumLV.as_view(), name='index'),

    #Example: /album/, same as /
    url(r'^album/$', AlbumLV.as_view(), name='album_list'),

    #Example: /album/99/
    url(r'^album/(?P<pk>\d+)/$', AlbumDV.as_view(), name='album_detail'),

    #Example: /photo/99/
    url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name='photo_detail'),

    # Example: /album/add/
    url(r'^album/add/$',
        AlbumPhotoCV.as_view(), name="album_add",
    ),

    # Example: /album/change/
    url(r'^album/change/$',
        AlbumChangeLV.as_view(), name="album_change",
    ),

    # Example: /album/99/update/
    url(r'^album/(?P<pk>[0-9]+)/update/$',
        AlbumPhotoUV.as_view(), name="album_update",
    ),

    # Example: /album/99/delete/
    url(r'^album/(?P<pk>[0-9]+)/delete/$',
        AlbumDeleteView.as_view(), name="album_delete",
    ),

    # Example: /photo/add/
    url(r'^photo/add/$',
        PhotoCreateView.as_view(), name="photo_add",
    ),

    # Example: /photo/change/
    url(r'^photo/change/$',
        PhotoChangeLV.as_view(), name="photo_change",
    ),

    # Example: /photo/99/update/
    url(r'^photo/(?P<pk>[0-9]+)/update/$',
        PhotoUpdateView.as_view(), name="photo_update",
    ),

    # Example: /photo/99/delete/
    url(r'^photo/(?P<pk>[0-9]+)/delete/$',
        PhotoDeleteView.as_view(), name="photo_delete",
    ),

]

photo/models.py
from django.db import models
from django.urls import reverse
from photo.fields import ThumbnailImageField

from django.contrib.auth.models import User

# Create your models here.

class Album(models.Model):
    name = models.CharField(max_length=50)
    description=models.CharField('One Line Description', max_length=100, blank=True)
    ##owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    class Meta:
        ordering=['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('photo:album_detail', args=(self.id,))


class Photo(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    image = ThumbnailImageField(upload_to='photo/%Y/%M')
    description = models.TextField('Photo Description', blank=True)
    upload_date = models.DateTimeField('Upload Date', auto_now_add=True)
    ##owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    class Meta:
        ordering=['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=(self.id,))

photo/forms.py
from photo.models import Album, Photo
from django.forms.models import inlineformset_factory

PhotoInlineFormSet = inlineformset_factory(Album, Photo,
    fields = ['image', 'title', 'description'],
    extra = 2)

mysite/views.py
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

from django.contrib.auth.decorators import login_required
#Create your views here.

#--- TemplateView
class HomeView(TemplateView):
    template_name = 'mainpage_ex.html'

class UserCreateView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')

class UserCreateDoneTV(TemplateView):
    template_name = 'registration/register_done.html'

class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return login_required(view)

photo/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from photo.models import Album, Photo
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from mysite.views import LoginRequiredMixin

# Create your views here.

class AlbumLV(ListView):
    model = Album

class AlbumDV(DetailView):
    model = Album

class PhotoDV(DetailView):
    model = Photo

#--- Add/Change/Update/Delete for Photo
class PhotoCreateView(LoginRequiredMixin, CreateView):
    model = Photo
    fields = ['album', 'title', 'image', 'description']
    success_url = reverse_lazy('photo:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(PhotoCreateView, self).form_valid(form)

class PhotoChangeLV(LoginRequiredMixin, ListView):
    template_name = 'photo/photo_change_list.html'

    def get_queryset(self):
        return Photo.objects.filter(owner=self.request.user)

class PhotoUpdateView(LoginRequiredMixin, UpdateView) :
    model = Photo
    fields = ['album', 'title', 'image', 'description']
    success_url = reverse_lazy('photo:index')

class PhotoDeleteView(LoginRequiredMixin, DeleteView) :
    model = Photo
    success_url = reverse_lazy('photo:index')

#--- Add/Change/Update/Delete for Album
#--- Change/Delete for Album
class AlbumChangeLV(LoginRequiredMixin, ListView):
    template_name = 'photo/album_change_list.html'

    def get_queryset(self):
        return Album.objects.filter(owner=self.request.user)

class AlbumDeleteView(LoginRequiredMixin, DeleteView) :
    model = Album
    success_url = reverse_lazy('photo:index')


#--- InlineFormSet View
#--- Add/Update for Album
from django.shortcuts import redirect
from photo.forms import PhotoInlineFormSet

class AlbumPhotoCV(LoginRequiredMixin, CreateView):
    model = Album
    fields = ['name', 'description']

    def get_context_data(self, **kwargs):
        context = super(AlbumPhotoCV, self).get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES)
        else:
            context['formset'] = PhotoInlineFormSet()
        return context

    def form_valid(self, form):
        form.instance.owner = self.request.user
        context = self.get_context_data()
        formset = context['formset']
        for photoform in formset:
            photoform.instance.owner = self.request.user
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect('photo:album_detail', pk=self.object.id)
        else:
            return self.render_to_response(self.get_context_data(form=form))

class AlbumPhotoUV(LoginRequiredMixin, UpdateView):
    model = Album
    fields = ['name', 'description']

    def get_context_data(self, **kwargs):
        context = super(AlbumPhotoUV, self).get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else:
            context['formset'] = PhotoInlineFormSet(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.object.get_absolute_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))




photo/templates/photo/album_detail.html
<!DOCTYPE html>
<html lang = "en">
    <head>
        <title>DONOR-HUB</title>
        <meta charset = "utf-8">
        <meta name = "viewport" content = "weidth=device-width, initial-scale = 1">
        <!-- Latest compiled and minified CSS -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <style>
            .jumbotron{
                background-color: orangered;
                color:white;
            }
            .bg-grey{
                background-color: #f6f6f6;
            }
            .container-fluid{
                padding: 60px 50px
            }
            .logo{
                color: orangered;
                font-size : 200px;
            }
            .logo-small{
                color:orangered;
                font-size: 50px;
            }
            .thumbnail{
                padding: 0 0 15px 0 ;
                border: none;
                border-radius: 0;
            }
            .thumbnail img{
                width: 100%;
                height: 300px;
                margin-bottom: 10px;
            }
            .carousel-control, .carousel-control.left{
                background-image: none;
                color: #f4511e;
            }
            .carousel-indicators li{
                border-color: #f4511e;
            }
            .carousel-indicators li.active{
                background-color: #f4511e;
            }
            .item h4{
                font-size: 19px;
                font-style: italic;
                margin: 70px 0;
            }
            #myCarousel2_img{
                width: 400px;
                height: 230px;
                margin-left: auto;
                margin-right: auto;
            }
            .panel{
                border: 1px solid #f4511e;
                border-radius:0;
                transiti on: box-shadow 0.5s;
            }
            .panel:hover{
                box-shadow: 5px 5px 40px lightgray;
            }
            .panel-footer .btn:hover{
                border: 1px solid #f4511e;
                background-color: #fff;
                color: #f4511e;
            }
            .panel-heading{
                color: #f4511e !important;
                background-color:#f4511e !important;
                padding: 25px;
            }
            .panel-footer{
                background-color: #fff !important;
            }
            .panel-footer h3{
                font-size: 32px;
            }
            .panel-footer h4{
                color: #aaa;
                font-size: 14px;
            }
            .panel-footer .btn{
                margin: 15px 0;
                background-color: #f4511e;
                color: #fff;
            }
            .navbar{
                background-color: #fff;
                border: 0;
                font-size: 12px;
                letter-spacing: 4px;
            }
            .navbar li a, .navbar .navbar-brand{
                color: #f4511e !important;
            }
            .navbar-nav li a:hover, .navbar-nav li.active a{
                color: #fff !important;
                background-color: #f4511e !important;
             }
            .navbar-default .navbar-toggle{
                border-color: transparent;
            }
            footer .glyphicon{
                font-size: 20px;
                margin-bottom: 20px;
                color: #f4511e;
            }
            body{
                font-family: Lato, sans-serif;
            }
            .jumbotron{
                font-family: Montserrat, sans-serif;
            }
            .navbar{
                font-family: Montserrat, sans-serif;
            }
            .card {
                /* Add shadows to create the "card" effect */
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                transition: 0.3s;
            }

            /* On mouse-over, add a deeper shadow */
            .card:hover {
                box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
            }

            /* Add some padding inside the card container */
            .card-size {
                padding: 2px 2px;
                width: 400px;
                height: 230px;
            }

            /* album_list.html */
            div.album-list{
                margin: 20px 50px;
            }

            div.album-list-photo{
                float: left;
                width: 150px;
                height: 180px;
            }


            /* album_detail.html */
            div.album-detail{
                margin: 30px 10px;
            }

            div.album-detail-photo{
                float: left;
                width: 220px;
                height: 220px;
            }

            div.album-detail-photo>li{
                font-size: 10px;
                font-weight: bold;
                font-style: italic;
            }


        </style>
    </head>
    <body id="myPage" data-spy="scroll" data-target=".navbar">
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'mainpage_ex' %}">DONOR-HUB</a>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'mainpage_ex' %}">ABOUT</a></li>
                        <li><a href="{% url 'mainpage_ex' %}">PORTFOLIO</a></li>

                        {% if user.is.active %}
                        <li><a href="{% url 'password_change' %}">Change Password</a></li>
                        <li><a href="{% url 'logout' %}">LOGOUT</a></li>
                        {% else %}
                        <li><a href="{% url 'register' %}">JOIN</a></li>
                        <li><a href="{% url 'login' %}">LOGIN</a></li>
                        {% endif %}
                        <li><a href="{% url 'photo:index' %}">THE HUB</a></li>
                        {% firstof user.get_short_name user.get_username %}
                    </ul>

                </div>


            </div>
        </nav>
        <div id="signup" class="container-fluid text-center">
            <br><br>
            <h1>Welcome to the Hub.</h1>
            <form action="/action_page.php">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for specific items; e.g., black nike shoes  " name="search">
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                    </div>
                </div>
            </form>

            <div id="content">

                <h2 style="display:inline">{{ object.name }}</h2>
                &emsp;<b><i>{{ object.description }}</i></b>

                <hr>
                <div class="row">
                    {% for photo in object.photo_set.all %}
                    <div class="col-sm-3">
                        <div class = "panel panel-default text-center">

                            <div>
                                <a href="{{ photo.get_absolute_url }}">
                                    <img class="thumbnail" src="{{ photo.image.thumb_url }}" height="100%" width="100%">
                                </a>
                                <div class="caption">
                                    <h5><strong>Name: </strong> {{ photo.title }}</h5>
                                    <h5><strong>Condition: </strong> {{ photo.upload_date|date:"Y-m-d" }}</h5>
                                    <h3>Size 9</h3>
                                </div>
                            </div>
                            <div class = "panel-footer">
                                    <h6>#shoes #nike #hyperdunk #black</h6>
                                    <button class = "btn btn-lg"><a href="{{ photo.get_absolute_url }}">View</a></button>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>

            </div>

        </div>
    </body>
</html>

photo/templates/photo/album_list.html
<!DOCTYPE html>
<html lang = "en">
    <head>
        <title>DONOR-HUB</title>
        <meta charset = "utf-8">
        <meta name = "viewport" content = "weidth=device-width, initial-scale = 1">
        <!-- Latest compiled and minified CSS -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <style>
            .jumbotron{
                background-color: orangered;
                color:white;
            }
            .bg-grey{
                background-color: #f6f6f6;
            }
            .container-fluid{
                padding: 60px 50px
            }
            .logo{
                color: orangered;
                font-size : 200px;
            }
            .logo-small{
                color:orangered;
                font-size: 50px;
            }
            .thumbnail{
                padding: 0 0 15px 0 ;
                border: none;
                border-radius: 0;
            }
            .thumbnail img{
                width: 100%;
                height: 300px;
                margin-bottom: 10px;
            }
            .carousel-control, .carousel-control.left{
                background-image: none;
                color: #f4511e;
            }
            .carousel-indicators li{
                border-color: #f4511e;
            }
            .carousel-indicators li.active{
                background-color: #f4511e;
            }
            .item h4{
                font-size: 19px;
                font-style: italic;
                margin: 70px 0;
            }
            #myCarousel2_img{
                width: 400px;
                height: 230px;
                margin-left: auto;
                margin-right: auto;
            }
            .panel{
                border: 1px solid #f4511e;
                border-radius:0;
                transiti on: box-shadow 0.5s;
            }
            .panel:hover{
                box-shadow: 5px 5px 40px lightgray;
            }
            .panel-footer .btn:hover{
                border: 1px solid #f4511e;
                background-color: #fff;
                color: #f4511e;
            }
            .panel-heading{
                color: #f4511e !important;
                background-color:#f4511e !important;
                padding: 25px;
            }
            .panel-footer{
                background-color: #fff !important;
            }
            .panel-footer h3{
                font-size: 32px;
            }
            .panel-footer h4{
                color: #aaa;
                font-size: 14px;
            }
            .panel-footer .btn{
                margin: 15px 0;
                background-color: #f4511e;
                color: #fff;
            }
            .navbar{
                background-color: #fff;
                border: 0;
                font-size: 12px;
                letter-spacing: 4px;
            }
            .navbar li a, .navbar .navbar-brand{
                color: #f4511e !important;
            }
            .navbar-nav li a:hover, .navbar-nav li.active a{
                color: #fff !important;
                background-color: #f4511e !important;
             }
            .navbar-default .navbar-toggle{
                border-color: transparent;
            }
            footer .glyphicon{
                font-size: 20px;
                margin-bottom: 20px;
                color: #f4511e;
            }
            body{
                font-family: Lato, sans-serif;
            }
            .jumbotron{
                font-family: Montserrat, sans-serif;
            }
            .navbar{
                font-family: Montserrat, sans-serif;
            }
            .card {
                /* Add shadows to create the "card" effect */
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                transition: 0.3s;
            }

            /* On mouse-over, add a deeper shadow */
            .card:hover {
                box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
            }

            /* Add some padding inside the card container */
            .card-size {
                padding: 2px 2px;
                width: 400px;
                height: 230px;
            }

            /* album_list.html */
            div.album-list{
                margin: 20px 50px;
            }

            div.album-list-photo{
                float: left;
                width: 150px;
                height: 180px;
            }


            /* album_detail.html */
            div.album-detail{
                margin: 30px 10px;
            }

            div.album-detail-photo{
                float: left;
                width: 220px;
                height: 220px;
            }

            div.album-detail-photo>li{
                font-size: 10px;
                font-weight: bold;
                font-style: italic;
            }


            /* photo_detail.html */
            table.photo-detail{
                margin: 30px 50px 0 50px;
                border: 1px solid #CCC;
                padding: 20px 20px;
            }

            table.photo-detail td{
                width: 50%;
            }

            table.photo-detail ul li{
                font-weight: bold;
            }

            table.photo-detail ul p{
                font-style: italic;
            }

            /* common */
            img.thumbnail{
                border: 3px solid #CCC;
            }

            div.clear_float{
                clear: both;
            }

        </style>
    </head>
    <body id="myPage" data-spy="scroll" data-target=".navbar">
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'mainpage_ex' %}">DONOR-HUB</a>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'mainpage_ex' %}">ABOUT</a></li>
                        <li><a href="{% url 'mainpage_ex' %}">PORTFOLIO</a></li>

                        {% if user.is.active %}
                        <li><a href="{% url 'password_change' %}">Change Password</a></li>
                        <li><a href="{% url 'logout' %}">LOGOUT</a></li>
                        {% else %}
                        <li><a href="{% url 'register' %}">JOIN</a></li>
                        <li><a href="{% url 'login' %}">LOGIN</a></li>
                        {% endif %}
                        <li><a href="{% url 'photo:index' %}">THE HUB</a></li>
                        {% firstof user.get_short_name user.get_username %}
                    </ul>

                </div>


            </div>
        </nav>
        <div id="signup" class="container-fluid text-center">
            <br><br>
            <h1>Welcome to the Hub.</h1>
            <form action="/action_page.php">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for specific items; e.g., black nike shoes  " name="search">
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                    </div>
                </div>
            </form>
            <button class = "btn btn-default"><a href="{% url 'photo:photo_add' %}">ADD AN ITEM</a></button>

            <div id="content">

                {% for item in object_list %}

                <div class="clear_float">
                    <h2 style="display:inline"><a href="{% url 'photo:album_detail' item.id %}">{{item.name}}</a></h2>
                    &emsp;<b><i>{{ item.description }}</i></b>
                </div>

                <hr>

                <div class="album-list">
                    {% for photo in item.photo_set.all|slice:":4" %}

                    <div class = "col-sm-3">
                    <div class = "panel panel-default text-center">
                        <div>
                        <a href="{{ photo.get_absolute_url }}" target="_blank">
                          <img src="{{ photo.image.thumb_url }}" alt="shoes" style="width:100%">
                        </a>
                        <div class="caption">
                            <h5><strong>Name:</strong> Nike Hyperdunks</h5>
                            <h5><strong>Condition:</strong> Barely Used</h5>
                            <h3>Size 9</h3>
                        </div>
                        </div>
                        <div class = "panel-footer">
                            <h6>#shoes #nike #hyperdunk #black</h6>
                            <button class = "btn btn-lg"><a href="{{ photo.get_absolute_url }}">View</a></button>
                        </div>
                    </div>
                </div>






                    {% endfor %}
                </div>
                {% endfor %}

            </div>

        </div>
    </body>
</html>